### ISSUE TITLE
The image id '[ami-d10819a8]' does not exist

### ISSUE THREAD

**Issue by csampsonza** [virtualjj/automated-openvpnas-cloudflare-letsencrypt#1]
Trying to run your cloudformation template and I get the following error:
The image id '[ami-d10819a8]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: 241018eb-eead-49e3-ade4-f5cfad6a96a1; Proxy: null)

Can you give some assistance on which ami we need to use.

**Comment by virtualjj** [comment]
Thanks @csampsonza for checking out my repo! Unfortunately I haven't touched this for about five years now so things are stale. It looks like you were trying to deploy in region `us-west-2` and the AMI ID below is no longer available: https://github.com/virtualjj/automated-openvpnas-cloudflare-letsencrypt/blob/e83cc0608a786013737467dafe6666dcd8aafcfd/automated-openvpnas-cloudflare-letsencrypt.yml#L245 

You'll likely have to subscribe to the  [Marketplace OpenVPN AS](https://aws.amazon.com/marketplace/seller-profile?id=aac3a8a3-2823-483c-b5aa-60022894b89d&ref=dtl_B00MI40CAE) if you haven't already and then you'll need to change the AMI ID above to `ami-0d10bccf2f1a6d60b` for `us-west-2` (Oregon). 

There are likely other out of date issues with this template; I'll try to update when I get a chance but there are likely better, more updated resources available.

**Comment by csampsonza** [comment]
I also ran into an error where the return from the _aws ssm get-parameters_ call has changed.  So instead of the 4 field the secret has moved to the 7th.  Thanks anyway, great script to get started with, will close my issue.
